#!/usr/bin/env node

const p = require('path');
const fs = require('fs');
const CWD = process.cwd();
const ERROR_LOG_FILE = p.join(CWD, 'pre-commit-script.error.log');
const SCRIPTS = require(p.join(CWD, 'package.json'))['pre-commit-scripts'] || [];
const exec = require('child_process').exec;

function execScript(script) {
    return new Promise((resolve, reject) => {
        exec(script, (err, stdout, stderr) => {
            if (err) return reject(stderr);
            resolve(stdout);
        });
    });
}

Promise
    .all(SCRIPTS.map(execScript))
    .then(stdout => {
        try {
            fs.unlinkSync(ERROR_LOG_FILE);
        } catch (e) {}
        process.stdout.write(stdout.toString());
        process.exit(0);
    })
    .catch((stderr) => {
        const errString = stderr.toString();
        fs.writeFileSync(ERROR_LOG_FILE, errString);
        process.stderr.write(errString);
        process.stderr.write('Aborting commit due to pre-commit-scripts error.');
        process.exit(1);
    });
